### ISSUE TITLE
Unable to retrieve certain OGC bibliographic references

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/ogc-2D-Tile-Matrix-Set#5]
```
[relaton-ogc] WARNING: no match found online for OGC 08-015r4. The code must be exactly like it is on the standards website.
[relaton-ogc] WARNING: no match found online for OGC 08-005r4. The code must be exactly like it is on the standards website.
[relaton-ogc] WARNING: no match found online for OGC 19-014r1. The code must be exactly like it is on the standards website.
[relaton-ogc] WARNING: no match found online for OGC 20-040r3. The code must be exactly like it is on the standards website.
[relaton-ogc] WARNING: no match found online for OGC 20-092. The code must be exactly like it is on the standards website.
```

FYI @ghobona

**Comment by ronaldtse** [comment]
@andrew2net can you please help investigate why these documents aren't available? Is this because of https://github.com/relaton/relaton-ogc/issues/19 ?

**Comment by andrew2net** [comment]
@ronaldtse these documents absent in the [dataset](https://raw.githubusercontent.com/opengeospatial/NamingAuthority/master/incubation/bibliography/bibliography.json)
- `08-015r4` there is only `08-015r2`
- `08-005r4` there isn't anything like `08-005`
- `19-014r1` there is only `19-014r3`
- `20-040r3` there isn't anything like `20-040`
- `20-092` there isn't anything like `20-092`

**Comment by ronaldtse** [comment]
Oh my. Ping @ghobona.

**Comment by ghobona** [comment]
* `08-015r4` should be replaced with [18-005r5](https://docs.ogc.org/as/18-005r5/18-005r5.html). This is the latest version of Abstract Specification Topic 2.
* `08-005r4`, I agree there isn't anything like `08-005`. The text in the document uses the document number 08-005 to refer to Abstract Spec Topic 2. Therefore, references to `08-005` should also be changed to [18-005r5](https://docs.ogc.org/as/18-005r5/18-005r5.html).
* `19-014r1` there is only `19-014r3`. Yes, please replace with `19-014r3`.
* `20-040r3`, I agree there isn't anything like `20-040`. The document is however is [here](https://docs.ogc.org/as/20-040r3/20-040r3.html) but is not showing in the spec catalog.  @gbuehler can advise on this issue.
* `20-092`, I agree there isn't anything like `20-092`. I could not find `20-092` on the spec catalog nor on the OGC Portal. Since the CDB X content came from the CDB-X Sprint's GitHub repo https://github.com/sofwerx/cdb2-eng-report , @jerstlouis shall we change the `20-092` reference to the CDB-X Sprint's GitHub repo https://github.com/sofwerx/cdb2-eng-report instead?

**Comment by jerstlouis** [comment]
@ghobona About the CDB X Tech Sprint report, I had pointed this out previously to @gbuehler, @DavidFLOR and @cnreediii.
I am not sure if it ended up published as an OGC discussion paper? Probably best to check with them on the status.

**Comment by ghobona** [comment]
Thanks @jerstlouis . We have tracked down the Discussion Paper.

**Comment by ronaldtse** [comment]
I've updated the references according to https://github.com/metanorma/ogc-2D-Tile-Matrix-Set/issues/5#issuecomment-1138531509 .

Todos:

* @ghobona do we have a replacement for the 20-092/CDB-X discussion paper?
* @gbuehler can you advise on 20-040r3 missing from the spec catalog? (document is [here](https://docs.ogc.org/as/20-040r3/20-040r3.html))

**Comment by ghobona** [comment]
@ronaldtse ,

@ogcscotts is going to check the status of the paper with the editors (@cnreediii and @DavidFLOR).

**Comment by ronaldtse** [comment]
I can confirm that all references in this document are now fetchable. Thank you @ghobona and @gbuehler!
